### GET all vacancies
GET http://localhost:8080/vacancies
Accept: application/json


### GET vacancy by id
GET http://localhost:8080/vacancies/1
Accept: application/json


### POST create vacancy
POST http://localhost:8080/vacancies
Content-Type: application/json

{
  "id": 3,
  "title": "Engineer",
  "company": "Netflix"
}